// This file is automatically generated. Do not edit it directly.

type AuthStorage = {
  getItem: (key: string) => string | null | Promise<string | null>;
  setItem: (key: string, value: string) => void | Promise<void>;
  removeItem: (key: string) => void | Promise<void>;
};

// Some embedded localhost browsers isolate localStorage when TanStack changes
// routes. Mirror only local development sessions into chunked, same-site
// cookies so /auth and /app can share them. Production keeps the normal
// localStorage/preview broker behavior.
function localDevelopmentStorage(): AuthStorage {
  let local: Storage | null = null;
  try { local = window.localStorage ?? null; } catch { local = null; }
  const indexedDb = new Promise<IDBDatabase | null>(resolve => {
    try {
      const request = window.indexedDB.open('feabulk-auth', 1);
      request.onupgradeneeded = () => {
        if (!request.result.objectStoreNames.contains('sessions')) request.result.createObjectStore('sessions');
      };
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => resolve(null);
      request.onblocked = () => resolve(null);
    } catch { resolve(null); }
  });
  const readIndexedDb = async (key: string) => {
    const database = await indexedDb;
    if (!database) return null;
    return new Promise<string | null>(resolve => {
      const request = database.transaction('sessions', 'readonly').objectStore('sessions').get(key);
      request.onsuccess = () => resolve(typeof request.result === 'string' ? request.result : null);
      request.onerror = () => resolve(null);
    });
  };
  const writeIndexedDb = async (key: string, value: string) => {
    const database = await indexedDb;
    if (!database) return;
    await new Promise<void>(resolve => {
      const transaction = database.transaction('sessions', 'readwrite');
      transaction.objectStore('sessions').put(value, key);
      transaction.oncomplete = () => resolve();
      transaction.onerror = () => resolve();
      transaction.onabort = () => resolve();
    });
  };
  const removeIndexedDb = async (key: string) => {
    const database = await indexedDb;
    if (!database) return;
    await new Promise<void>(resolve => {
      const transaction = database.transaction('sessions', 'readwrite');
      transaction.objectStore('sessions').delete(key);
      transaction.oncomplete = () => resolve();
      transaction.onerror = () => resolve();
      transaction.onabort = () => resolve();
    });
  };
  const maxChunkLength = 2800;
  const cookieOptions = `Path=/; SameSite=Lax; Max-Age=${60 * 60 * 24 * 30}`;
  const cookieName = (key: string, suffix: string) => `feabulk_${key.replace(/[^a-zA-Z0-9_-]/g, "_")}_${suffix}`;
  const readCookie = (name: string) => {
    const prefix = `${name}=`;
    const part = document.cookie.split("; ").find(item => item.startsWith(prefix));
    return part ? part.slice(prefix.length) : null;
  };
  const clearCookies = (key: string) => {
    const count = Number(readCookie(cookieName(key, "count")) ?? 0);
    for (let index = 0; index < Math.max(count, 8); index += 1) {
      document.cookie = `${cookieName(key, String(index))}=; Path=/; SameSite=Lax; Max-Age=0`;
    }
    document.cookie = `${cookieName(key, "count")}=; Path=/; SameSite=Lax; Max-Age=0`;
  };
  const readCookieValue = (key: string) => {
    const count = Number(readCookie(cookieName(key, "count")) ?? 0);
    if (!Number.isInteger(count) || count < 1 || count > 20) return null;
    let encoded = "";
    for (let index = 0; index < count; index += 1) {
      const chunk = readCookie(cookieName(key, String(index)));
      if (chunk == null) return null;
      encoded += chunk;
    }
    try { return decodeURIComponent(encoded); } catch { return null; }
  };
  const writeCookieValue = (key: string, value: string) => {
    clearCookies(key);
    const encoded = encodeURIComponent(value);
    const count = Math.ceil(encoded.length / maxChunkLength);
    for (let index = 0; index < count; index += 1) {
      const chunk = encoded.slice(index * maxChunkLength, (index + 1) * maxChunkLength);
      document.cookie = `${cookieName(key, String(index))}=${chunk}; ${cookieOptions}`;
    }
    document.cookie = `${cookieName(key, "count")}=${count}; ${cookieOptions}`;
  };

  return {
    getItem: async key => local?.getItem(key) ?? await readIndexedDb(key) ?? readCookieValue(key),
    setItem: async (key, value) => {
      local?.setItem(key, value);
      writeCookieValue(key, value);
      await writeIndexedDb(key, value);
    },
    removeItem: async key => {
      local?.removeItem(key);
      clearCookies(key);
      await removeIndexedDb(key);
    },
  };
}

// On a Lovable preview surface, broker the auth session to the editor over
// postMessage so the project's preview surfaces share one login; else localStorage.
export function brokeredPreviewStorage(): AuthStorage | undefined {
  if (typeof window === 'undefined') return undefined;
  const host = location.hostname;
  if (host === 'localhost' || host === '127.0.0.1' || host === '::1') return localDevelopmentStorage();
  const PREVIEW_ZONES = ['lovableproject.com', 'lovableproject-dev.com', 'lovable.app', 'gpt-eng.com', 'gptengineer.run'];
  const onPreviewZone = PREVIEW_ZONES.some((z) => host === z || host.endsWith('.' + z));
  // Read the id only from non-user-controlled host positions, so a user-named
  // preview--<name> host can't smuggle another project's id.
  const UUID = '[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}';
  const projectId = onPreviewZone
    ? (host.match(new RegExp('^(?:id-preview(?:-[a-z0-9]+)?|project)--(' + UUID + ')(?:-dev)?(?=\\.|$)', 'i'))?.[1]
        ?? host.match(new RegExp('^(' + UUID + ')(?=[.-])', 'i'))?.[1])
    : undefined;
  const framed = window.parent && window.parent !== window;
  if (!projectId || !framed) return localStorage;

  // Post only to the real editor ancestor, validated as a Lovable origin, so the
  // session token can never reach an untrusted embedder.
  const dev = host.endsWith('.lovableproject-dev.com') || host.endsWith('.gpt-eng.com');
  const EDITOR = dev
    ? /^https:\/\/([a-z0-9-]+\.)*(lovable\.dev|gptengineer\.app)$|^http:\/\/localhost:3000$/
    : /^https:\/\/([a-z0-9-]+\.)*(lovable\.dev|gptengineer\.app)$/;
  const ancestor = (location.ancestorOrigins && location.ancestorOrigins[0]) || (document.referrer ? new URL(document.referrer).origin : '');
  const editorOrigins = ancestor && EDITOR.test(ancestor)
    ? [ancestor]
    : (dev ? ['https://lovable.dev', 'http://localhost:3000'] : ['https://lovable.dev']);
  const RESULT = 'lovable-preview-auth:result';
  const TIMEOUT = 2000;
  const newId = () => Math.random().toString(36).slice(2) + Date.now().toString(36);

  const request = (type: string, key: string, value?: string): Promise<{ ok: boolean; value?: string | null } | null> =>
    new Promise((resolve) => {
      const requestId = newId();
      let done = false;
      const finish = (r: { ok: boolean; value?: string | null } | null) => {
        if (done) return;
        done = true;
        clearTimeout(timer);
        window.removeEventListener('message', onMessage);
        resolve(r);
      };
      const onMessage = (e: MessageEvent) => {
        if (editorOrigins.indexOf(e.origin) < 0) return;
        const d = e.data;
        if (d && d.type === RESULT && d.requestId === requestId) finish(d);
      };
      window.addEventListener('message', onMessage);
      const msg: Record<string, unknown> = { type, requestId, projectId, key };
      if (value !== undefined) msg['value'] = value;
      const timer = setTimeout(() => finish(null), TIMEOUT);
      // targetOrigin per trusted editor origin, so a session token never reaches an arbitrary embedder.
      for (const origin of editorOrigins) window.parent.postMessage(msg, origin);
    });

  // The editor may not be listening yet at the first getItem, so retry once.
  let firstGet = true;
  const RETRY_DELAY = 250;

  return {
    getItem: async (key: string) => {
      let res = await request('lovable-preview-auth:get', key);
      if (!res && firstGet) {
        await new Promise((r) => setTimeout(r, RETRY_DELAY));
        res = await request('lovable-preview-auth:get', key);
      }
      firstGet = false;
      // '' is the logout tombstone: clear the local copy too so it can't resurrect if
      // the broker later goes silent. A null reply means never-synced -> keep local.
      if (res && res.ok && typeof res.value === 'string') {
        if (res.value === '') { localStorage.removeItem(key); return null; }
        return res.value;
      }
      return localStorage.getItem(key);
    },
    setItem: (key: string, value: string) => {
      localStorage.setItem(key, value);
      return request('lovable-preview-auth:set', key, value).then(() => undefined);
    },
    removeItem: (key: string) => {
      localStorage.removeItem(key);
      return request('lovable-preview-auth:remove', key).then(() => undefined);
    },
  };
}
